server:
    port: 9910
    tomcat:
        remoteip:
            remote-ip-header: "x-forwarded-for"
            protocol-header: "x-forwarded-proto"

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://rm-2ze284i1ed8sd1qu1125010.mysql.rds.aliyuncs.com:3306/qywx_third_demo_h5?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: tobdev_third_demo
        password: demo_20201206
    redis:
        ## Redis数据库索引（默认为0）
        database: 0
        ## Redis服务器地址
        host: 127.0.0.1
        ## Redis服务器连接端口
        port: 6379
        ## Redis服务器连接密码（默认为空）
        password:
        timeout: 0
        pool:
            max-active: 1000
            max-wait: 1
            max-idle: 10
            min-idle: 2

mybatis:
    configuration:
        ##控制台sql
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        ##数据库字段下划线与驼峰
        map-underscore-to-camel-case: true
        ##mapper扫码路径
    mapper-locations: classpath:mapper/*.xml
    ##xml配置别名
    type-aliases-package: com.tobdev.qywxthird.model.entity




qywx-third:
    corpId: "wwae6d661c97e24e98"
    providerSecret: "Vb316P2abRv8isjpbHvvXFPG5DgbVdVmCPqZqjWoZt1j9VcV7e2A67t2a1YlxlAg"
    suiteId: "wwd0a77c3eb62b965c"
    suiteSecret: "0C8maOs57u7e4qmTh13NAJUCvpMDwihLg4XYEn3MsvE"
    token: "ojF7qraz6kwgefFDJh6tKhZvDtokP9L"
    encodingAESKey: "Z6Cb64Q6GbDcmuqrILUSlCy5e1o2aZYkB226RimVFpw"
    authType: 1
    #推广码id 需先上线
    templateId: ""
    #审批流程引擎 审批模板id
    approvalFlowId: "58f08820708c9ba41dae790956982941_691929339"
ddß
qywx-cache:
    keyPrefix: "h5-"
    suitTicket: "suite-ticket"